apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mofwili/k8s-gitops.git
    targetRevision: main
    path: .
    plugin:
      name: ytt   # requires ArgoCD ytt plugin installed (or use kustomize + ytt cmd)
      # If no plugin: use post-render or sidecar approach
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
