apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-artifact-repositories
  namespace: argo
  labels:
    workflows.argoproj.io/configmap-type: ArtifactRepository
data:
  default: |
    s3:
      bucket: pipeline-artifacts
      endpoint: 10.4.13.26:9000  # Change from 30633 to 9000
      insecure: true
      accessKeySecret:
        name: minio-credentials
        key: accesskey
      secretKeySecret:
        name: minio-credentials
        key: secretkey
      keyFormat: "{{workflow.namespace}}/{{workflow.name}}/{{pod.name}}/{{artifact.name}}"
